# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Exercise.create!([
    { name: 'Shoulder Rolls' , category: 'Warm Up', reps: '5-10', example: 'https://www.youtube.com/embed/H01oGIS1C_g', progression: 'Level 1' },
    { name: 'Scapular Shrugs' , category: 'Warm Up', reps: '5-10', example: 'https://www.youtube.com/embed/akgQbxhrhOc', progression: 'Level 1' },
    { name: 'Cat-Camels' , category: 'Warm Up', reps: '5-10', example: 'http://www.youtube.com/embed/K9bK0BwKFjs', progression: 'Level 1' },
    { name: 'Band: Straight Arm Overhead Pull Downs' , category: 'Warm Up', reps: '5-10', example: 'https://www.youtube.com/embed/8lDC4Ri9zAQ', progression: 'Level 1' },
    { name: 'Band: Straight Arm Chest Flies' , category: 'Warm Up', reps: '5-10', example: 'https://www.youtube.com/embed/8lDC4Ri9zAQ', progression: 'Level 1' },
    { name: 'Band: Dislocates' , category: 'Warm Up', reps: '5-10', example: 'https://www.youtube.com/embed/8lDC4Ri9zAQ', progression: 'Level 1' },
    { name: 'Wrist Mobility Exercises' , category: 'Warm Up', reps: '10+', example: 'https://www.youtube.com/embed/mSZWSQSSEjE', progression: 'Level 1' },
    { name: 'Front and Side Leg Swings' , category: 'Warm Up', reps: '5-10', example: 'https://www.youtube.com/embed/AkqakLhh1fI', progression: 'Level 1' },
    { name: 'Plank' , category: 'Core Warm Up', reps: '10-60 sec', example: 'https://www.youtube.com/embed/44ScXWFaVBs', progression: 'Level 1' },
    { name: 'Side Plank' , category: 'Core Warm Up', reps: '10-60 sec', example: 'https://www.youtube.com/embed/44ScXWFaVBs', progression: 'Level 1' },
    { name: 'Reverse Plank' , category: 'Core Warm Up', reps: '10-60 sec', example: 'https://www.youtube.com/embed/44ScXWFaVBs', progression: 'Level 1' },
    { name: 'Hollow Hold' , category: 'Core Warm Up', reps: '10-60 sec', example: 'https://www.youtube.com/embed/44ScXWFaVBs', progression: 'Level 1' },
    { name: 'Arch Hold' , category: 'Core Warm Up', reps: '10-60 sec', example: 'https://www.youtube.com/embed/44ScXWFaVBs', progression: 'Level 1' },
    { name: 'Parallel Bar Support' , category: 'Support Progression', reps: '2-3 min', example: 'https://www.youtube.com/embed/IbWE49HdsrE', progression: 'Level 1' },
    { name: 'Ring Support Hold' , category: 'Support Progression', reps: '2-3 min', example: 'https://www.youtube.com/embed/C07M-t0_Vxg', progression: 'Level 2' },
    { name: 'Ring Turned Out Support Hold' , category: 'Support Progression', reps: '2-3 min', example: 'https://www.youtube.com/embed/8gmyhBScTLk', progression: 'Level 3' },
    { name: 'Wall Plank' , category: 'Handstand Progression', reps: '5-10 min', example: 'https://www.youtube.com/embed/6jm4R3K4sJA', progression: 'Level 1' },
    { name: 'Wall Handstand' , category: 'Handstand Progression', reps: '5-10 min', example: 'https://www.youtube.com/embed/m64XxmNHjfs', progression: 'Level 2' },
    { name: 'Freestanding Handstand' , category: 'Handstand Progression', reps: '5-10 min', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 3' },
    { name: 'Pull-Up Negatives' , category: 'Pull-Up Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 1' },
    { name: 'Pull-Ups' , category: 'Pull-Up Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 2' },
    { name: 'L-Sit Pull-Ups' , category: 'Pull-Up Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 3' },
    { name: 'Bar Pull-Overs' , category: 'Pull-Up Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 4' },
    { name: 'Parallel Bar-Dips' , category: 'Dipping Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 1' },
    { name: 'Ring Dips' , category: 'Dipping Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 2' },
    { name: 'Foot Supported L-Sit' , category: 'L-Sit Progression', reps: '3x10sec-30sec', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 1' },
    { name: 'One Leg Foot Supportes L-Sit' , category: 'L-Sit Progression', reps: '3x10sec-30sec', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 2' },
    { name: 'Tuck L-Sit' , category: 'L-Sit Progression', reps: '3x10sec-30sec', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 3' },
    { name: 'L-Sit' , category: 'L-Sit Progression', reps: '3x10sec-30sec', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 4' },
    { name: 'Assisted Squat' , category: 'Squat Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 1' },
    { name: 'Squat' , category: 'Squat Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 2' },
    { name: 'Step-Ups' , category: 'Squat Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 3' },
    { name: 'Deep Step-Ups' , category: 'Squat Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 4' },
    { name: 'Vertical Pushup' , category: 'Push-Up Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 1' },
    { name: 'Incline Pushup' , category: 'Push-Up Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 2' },
    { name: 'Full Pushup' , category: 'Push-Up Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 3' },
    { name: 'Diamond Pushup' , category: 'Push-Up Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 4' },
    { name: 'Rings Wide Pushup' , category: 'Push-Up Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 5' },
    { name: 'Rings Pushup' , category: 'Push-Up Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 6' },
    { name: 'Vertical Rows' , category: 'Row Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 1' },
    { name: 'Incline Rows' , category: 'Row Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 2' },
    { name: 'Horizontal Rows' , category: 'Row Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 3' },
    { name: 'Wide Rows' , category: 'Row Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 4' },
    { name: 'Tuck Front Lever' , category: 'Row Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 5' },
    { name: 'Tuck Ice Cream Maker' , category: 'Row Progression', reps: '3x5-8', example: 'https://www.youtube.com/embed/N3K9SMNKL7', progression: 'Level 6' },
])